name:                evm
version:             0.1.0.0
github:              "githubuser/evm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/evm#readme>

dependencies:
- base >= 4.7 && < 5
- cryptohash 
- bytestring
- hex
- finite-field >= 0.8.0
- modular-arithmetic >= 1.2.1.3
  # - glpk-hs-0.1.0]

library:
  source-dirs: src

executables:
  evm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evm

tests:
  evm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evm
